networks:
  classpay:
    driver: bridge

volumes:
  classpay-db:
    driver: local
  classpay-redis:
    driver: local  # Persistent storage for Redis

services:
  db:
    image: postgres:alpine
    container_name: classpay-db
    environment:
      - TZ=Asia/Yangon
      - POSTGRES_DB=classpay_db
      - POSTGRES_USER=classpayusr
      - POSTGRES_PASSWORD=classpaypwd
    networks:
      - classpay
    ports:
      - 5432:5432
    volumes:
      - classpay-db:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: classpay-redis
    networks:
      - classpay
    ports:
      - 6379:6379
    volumes:
      - classpay-redis:/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: classpay-app
    depends_on: # Ensures that services start before the app tries to connect
      - db
      - redis
    networks:
      - classpay
    ports:
      - 8080:8080
